#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
   echo "Aborting commit, your commit message do not adhere to the guidelines" >&2
   exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,100}$"; then
   echo "Aborting commit, commit messages cannot contain more than 100 characters" >&2
   exit 1
fi